services:
  floci-gcp:
    image: floci/floci-gcp:latest
    container_name: floci-gcp
    ports:
      - "4588:4588"
    volumes:
      - ./floci-data/gcp:/app/data
    environment:
      FLOCI_GCP_HOSTNAME: floci-gcp
      FLOCI_GCP_BASE_URL: http://floci-gcp:4588
      FLOCI_GCP_STORAGE_MODE: hybrid

  floci:
    image: floci/floci:latest
    container_name: floci-aws
    ports:
      - "4566:4566"
      - "9092:9092"
    volumes:
      - ./floci-data/aws:/app/data
      - //var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - redpanda

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --overprovisioned
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://localhost:19092
    ports:
      - "19092:9092"